---
# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
                # -   id: check-yaml
            #     args: [--unsafe]
      - id: check-added-large-files
    # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
    # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc
        args: [--check --diff]
    # this should be run before flake8 to
    # this should be run externally
    # messes up too many things
    # - repo: https://github.com/PyCQA/docformatter
    #   rev: v1.5.0
    #   hooks:
    #     - id: docformatter
    #       args: [--in-place]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: ^src/cmomy/tests/|^docs/conf.py|^setup.py

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
            # `properies` & `asv_bench` are copied from setup.cfg.
            # `_typed_ops.py` is added since otherwise mypy will complain (but notably only in pre-commit)
        exclude: properties|asv_bench|_typed_ops.py|conf.py
            # This is slow and so we take it out of the fast-path; requires passing
            # `--hook-stage manual` to pre-commit
        stages: [manual]
        additional_dependencies: [types-pkg_resources, typing-extensions==3.10.0.0,
          numpy]

    # run this occasionally, ref discussion https://github.com/pydata/xarray/pull/3194
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.22.1
    hooks:
      - id: pyupgrade
        stages: [manual]
        args:
          - --py3-only
                # remove on f-strings in Py3.7
          - --keep-percent-format
