---
# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.2.2
    hooks:
      - id: validate_manifest
  ## formatting
  # prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        stages: [commit]
        additional_dependencies:
          - prettier-plugin-toml
        exclude: ^docs/reference/
  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.261"
    hooks:
      - id: ruff
        args: ["--fix"]
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [manual]
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.13.0" # replace with latest tag on GitHub
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.1.0
        exclude: ^README.md
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc
        additional_dependencies: ["black==23.3.0"]
      - id: blackdoc-autoupdate-black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        types_or: [python, rst, markdown, cython, c]
        additional_dependencies: [tomli]
        args: [-I, docs/spelling_wordlist.txt]
        stages: [manual]
  # TODO: Consider moving to flakeheaven
  # see https://github.com/rstcheck/rstcheck/blob/main/.pre-commit-config.yaml
  # see https://flakeheaven.readthedocs.io/en/latest/config.html
  # - repo: https://github.com/flakeheaven/flakeheaven
  #   rev: 3.3.0
  #   hooks:
  #     - id: flakeheaven
  #       types_or: [python, jupyter, markdown, rst, yaml]
  #       stages: [manual]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [manual]
        additional_dependencies:
          - flake8-docstrings
          # - pep8-naming
          # - flake8-rst-docstrings
        exclude: ^tests/|^src/{{ cookiecutter.project_slug }}/tests/|^docs/conf.py|^setup.py
  # Manual mypy
  - repo: local
    hooks:
      - id: mypy
        # note: assumes python env is setup and activated
        name: mypy
        entry: tox
        args: ["-e", "lint-mypy"]
        language: system
        pass_filenames: false
        # additional_dependencies: [tox]
        types: [python]
        require_serial: true
        stages: [manual]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        stages: [manual]
        args:
          - --py38-plus
          # remove on f-strings in Py3.7
          - --keep-percent-format

  # commit message
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v2.42.1
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]
  # - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  #   rev: v9.5.0
  #   hooks:
  #     - id: commitlint
  #       stages: [commit-msg]
  # - repo: https://github.com/jorisroovers/gitlint
  #   rev:  v0.19.1
  #   hooks:
  #   - id: gitlint
