test:
  imports:
    - {{ cookiecutter.project_slug }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name}}
  summary: {{ cookiecutter.project_short_description }}
  description: |
    {{ cookiecutter.project_short_description }}
  license: {{ cookiecutter.open_source_license }}
  license_file: LICENSE

extra:
  recipe-maintainers:
    - {{ cookiecutter.github_username }}
