name: {{ cookiecutter.project_slug }}-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python=3.8
  # because using scm versioning
  - setuptools>=38.4
  # cli
  {% if cookiecutter.command_line_interface|lower == 'click' -%}
  - Click{% endif %}
  {% if cookiecutter.command_line_interface|lower == 'fire' -%}
  - fire{% endif %}
