dependencies:
    # recommendation is to install linteres, etc with pipx
    # and to handle documentation and building with tox
    # in an isolated env
    ## specials
    # - pre-commit
    ## Linting
    # - isort
    # - black
    # - blackdoc
    # - flake8
    # - autoflake
    ## flake8 options
    # - flake8-docstrings
    ## testing
    - pytest
    - pytest-cov
    ## optional pytest
    # - pytest-xdist
    # - pytest-flake8
    # - tox-conda
    ## optional tox stuff
    ## Don't think I need tox-conda if specify in tox.ini file
    # - tox-conda
    ## repl
    - ipython
    - ipykernel
    ## build
    - setuptools-scm
    # - setuptools
    # - setuptools_scm_git_archive
    # - build
    # - twine
    ## conda specific
    # - conda-build
    # - anaconda-client
    # - grayskull
    ## doc stuff
    # - sphinx
    # - sphinx_rtd_theme
    # - nbsphinx # if want notebooks
    # - sphinxcontrib-spelling
    # - pip
    # - pip:
    #         ## spell checking with sphinx?
    #         - pyenchant
