dependencies:
  ## development
  - isort
  - black
  - blackdoc
  - flake8
  ## flake8 options
  # - flake8-docstrings
  ## testing
  - pytest
  - pytest-cov
  ## optional pytest
  # - pytest-xdist
  # - pytest-flake8
  - tox
  ## optional tox stuff
  ## Don't think I need tox-conda if specify in tox.ini file
  # - tox-conda
  ## specials
  - pre-commit
  ## repl
  - ipython
  - ipykernel
  ## build
  - setuptools
  - setuptools-scm
  - setuptools_scm_git_archive
  - build
  - twine
  ## conda specific
  - conda-build
  - anaconda-client
  - greyskull
  ## doc stuff
  - sphinx
  - sphinx_rtd_theme
  - recommonmark # if want markdown
  - nbsphinx # if want notebooks
  ## lsp stuff
  - autoflake
  - pyls-mypy
  - pyls-black
  - pyls-isort
