name: {{ cookiecutter.project_slug }}-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python>=3.8,<3.11
  # cli
  {% if cookiecutter.command_line_interface|lower == 'click' -%}
  - Click{% endif %}
  {% if cookiecutter.command_line_interface|lower == 'fire' -%}
  - fire{% endif %}
