# Handle anything that we want to do with the template.
# NOTE: Can't do this in .pre-commit-config.yaml because
# have global exclude `^{{cookiecutter.project_name}}$`.
# If remove this, then have to perform exclude it for most hooks.

repos:
  # * sync dependencies
  - repo: https://github.com/wpk-nist-gov/sync-pre-commit-hooks
    rev: v0.8.1
    hooks:
      - id: sync-pyproject-min-versions
        files: ^{{cookiecutter.project_name}}/pyproject\.toml$|^requirements/lock/uvx-tools\.txt$|^{{cookiecutter.project_name}}/noxfile\.py$|^{{cookiecutter.project_name}}/tools/.*\.py$
        args:
          - "--requirements=requirements/lock/uvx-tools.txt"
