# This file is an example for setting user specific config
# for use with nox.  Copy this file to `config/noxconfig.toml` in the
# root of the repo.  The file `config/noxconfig.toml` should NOT be tracked.
#
# This should point to (globbed version) of location of python executables
# to be used in creating of virtualenv.
# For example, this could be paths = ["~/miniforge3/envs/test-3.*/bin"]
[nox.python]
paths = ["~/.conda/envs/test-3.*/bin"]

# Extras for environments
# for example, could have
#
# dev = ["dev", "nox", "tools"]
#
# The value in the list are `extras` in the pyproject.toml file
# which will be included when creating environment/*.yaml files.
[nox.extras]
dev = ["dev", "nox"]
