# This file is for setting user specific config for use
# with nox and other project tools and applications.
#
# THIS FILE SHOULD NOT BE TRACKED BY GIT!!!!
#
# Example usage:
#
# [nox.python]
# paths = ["~/.conda/envs/test-3.*/bin"]
#
# [nox.extras]
# dev = ["dev-complete"]
[nox.python]
paths = ["~/.conda/envs/test-3.*/bin"]

[nox.extras]
dev = ["dev", "nox"]

