name: Setup cached uv and python
description:
  Composite action to do 'actions/setup-python' and 'hynek/setup-cached-uv'
inputs:
  # actions/setup-python

  python-version:
    description: "Version to pass to actions/setup-python"
  python-version-file:
    description: "File to pass to actions/setup-python"
  # hynek/setup-cached-uv
  cache-dependency-path:
    description: "Passed to hynek/setup-cached-uv"
    required: false
    default: "pyproject.toml"

outputs:
  python-version:
    description:
      "The installed Python or PyPy version. Useful when given a version range
      as input."
    value: {% raw %}${{ steps.setup-python.outputs.python-version }}{% endraw %}
  cache-hit:
    description: "A boolean value to indicate a cache entry was found"
    value: {% raw %}${{ steps.setup-python.outputs.cache-hit }}{% endraw %}
  python-path:
    description: "The absolute path to the Python or PyPy executable."
    value: {% raw %}${{ steps.setup-python.outputs.pytyhon-path }}{% endraw %}

runs:
  using: composite
  steps:
    - name: Setup python
      id: setup-python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: {% raw %}${{ inputs.python-version }}{% endraw %}
        python-version-file: {% raw %}${{ inputs.python-version-file }}{% endraw %}
    - name: Setup cached uv
      id: setup-cached-uv
      uses: hynek/setup-cached-uv@757bedc3f972eb7227a1aa657651f15a8527c817 # v2.3.0
      with:
        cache-dependency-path: {% raw %}${{ inputs.cache-dependency-path }}{% endraw %}
