test:
  imports:
    - {{ cookiecutter.project_slug }}
  commands:
    - pip check
  requires:
    - pip
{%- raw %}
    - python {{ python_min }}
{%- endraw %}

about:
  home: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name}}
  summary: {{ cookiecutter.project_short_description }}
  description: |
    {{ cookiecutter.project_short_description }}
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - {{ cookiecutter.github_username }}
