# This file is an example for setting user specific config
# for use with nox.  Copy this file to `config/userconfig.toml` in the
# root of the repo.  The file `config/userconfig.toml` should NOT be tracked.
#
# This file can also be created using
#
# python tools/projectconfig.py -p {pattern1, ...} -d {extra1, extras2, ...}
#
# This should point to (globbed version) of location of python executables
# For example, this could be paths = ["~/miniforge3/envs/python-3.*/bin"]
[nox.python]
paths = ["~/.conda/envs/python-3.*/bin"]

# Extras for environments (see https://github.com/usnistgov/pyproject2conda)
# Override dev environemt extras for user.
[tool.pyproject2conda.envs.dev]
dev = ["dev", "nox", "tools"]
